### ISSUE TITLE
Autoparams does not work with Java Records

### ISSUE THREAD

**Issue by lucas-dclrcq** [JavaUnit/AutoParams#279]
Hello,

I would like to use autoparams in a Java 17 project, but it seems the library cannot generate records.

When running the following test :

```java
import org.javaunit.autoparams.AutoSource;
import org.junit.jupiter.params.ParameterizedTest;

import static org.assertj.core.api.Assertions.assertThat;

class TestRecordAutoparams {
    record TestRecord(String a, Long b) { }

    @ParameterizedTest
    @AutoSource
    void name(TestRecord testRecord) {
        assertThat(testRecord).isNotNull();
    }
}
```

It fails with the following stacktrace :

```
java.lang.RuntimeException: Class 'com.adeo.toa.backend.core.domain.model.notification.TestRecordAutoparams$TestRecord' has no public constructor.

	at org.javaunit.autoparams.generator.ComplexObjectGenerator.lambda$resolveConstructor$4(ComplexObjectGenerator.java:77)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.javaunit.autoparams.generator.ComplexObjectGenerator.resolveConstructor(ComplexObjectGenerator.java:76)
	at org.javaunit.autoparams.generator.ComplexObjectGenerator.generateNonGeneric(ComplexObjectGenerator.java:35)
	at org.javaunit.autoparams.generator.ComplexObjectGenerator.generate(ComplexObjectGenerator.java:22)
	at org.javaunit.autoparams.generator.CompositeObjectGenerator.lambda$null$0(CompositeObjectGenerator.java:16)
	at org.javaunit.autoparams.generator.ObjectContainer.yieldIfEmpty(ObjectContainer.java:17)
	at org.javaunit.autoparams.generator.CompositeObjectGenerator.lambda$generate$1(CompositeObjectGenerator.java:16)
	at org.javaunit.autoparams.generator.Folder.foldl(Folder.java:13)
	at org.javaunit.autoparams.generator.CompositeObjectGenerator.generate(CompositeObjectGenerator.java:15)
	at org.javaunit.autoparams.customization.RecursionGuard.lambda$customize$2(RecursionGuard.java:67)
	at org.javaunit.autoparams.generator.CompositeObjectGenerator.lambda$null$0(CompositeObjectGenerator.java:16)
	at org.javaunit.autoparams.generator.ObjectContainer.yieldIfEmpty(ObjectContainer.java:17)
	at org.javaunit.autoparams.generator.CompositeObjectGenerator.lambda$generate$1(CompositeObjectGenerator.java:16)
	at org.javaunit.autoparams.generator.Folder.foldl(Folder.java:13)
	at org.javaunit.autoparams.generator.CompositeObjectGenerator.generate(CompositeObjectGenerator.java:15)
	at org.javaunit.autoparams.generator.CompositeObjectGenerator.lambda$null$0(CompositeObjectGenerator.java:16)
	at org.javaunit.autoparams.generator.ObjectContainer.yieldIfEmpty(ObjectContainer.java:17)
	at org.javaunit.autoparams.generator.CompositeObjectGenerator.lambda$generate$1(CompositeObjectGenerator.java:16)
	at org.javaunit.autoparams.generator.Folder.foldl(Folder.java:13)
	at org.javaunit.autoparams.generator.CompositeObjectGenerator.generate(CompositeObjectGenerator.java:15)
	at org.javaunit.autoparams.generator.ObjectGenerationContext.generateObject(ObjectGenerationContext.java:44)
	at org.javaunit.autoparams.generator.ObjectGenerationContext.generate(ObjectGenerationContext.java:38)
	at org.javaunit.autoparams.ArgumentsGenerator.createThenProcessArgument(ArgumentsGenerator.java:98)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at org.javaunit.autoparams.ArgumentsGenerator.createArguments(ArgumentsGenerator.java:93)
	at org.javaunit.autoparams.ArgumentsGenerator.generate(ArgumentsGenerator.java:84)
	at org.javaunit.autoparams.ArgumentsGenerator.generateArguments(ArgumentsGenerator.java:36)
	at org.javaunit.autoparams.AutoArgumentsProvider.provideArguments(AutoArgumentsProvider.java:29)
	at org.junit.jupiter.params.ParameterizedTestExtension.arguments(ParameterizedTestExtension.java:137)
	at org.junit.jupiter.params.ParameterizedTestExtension.lambda$provideTestTemplateInvocationContexts$2(ParameterizedTestExtension.java:88)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:107)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:42)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
	Suppressed: org.junit.platform.commons.PreconditionViolationException: Configuration error: You must configure at least one set of arguments for this @ParameterizedTest
		at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:281)
		at org.junit.jupiter.params.ParameterizedTestExtension.lambda$provideTestTemplateInvocationContexts$6(ParameterizedTestExtension.java:94)
		at java.base/java.util.stream.AbstractPipeline.close(AbstractPipeline.java:323)
		at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
		... 53 more
```

Do you plan to support Java > 8 features in the near future ?

If I want to contribute support for records, what do I need to know to get started ?

Best regards,

Lucas

**Comment by gyuwon** [comment]
I'm really sorry for not responding for so long. 🙏
Please let me test with record first.

**Comment by gyuwon** [comment]
https://github.com/AutoParams/AutoParams/blob/440fc45b6291e302f027d7f945775148e2629acd/autoparams-test-java17/src/test/java/test/autoparams/SpecsForAutoSource.java#L10-L14

@lucas-dclrcq I apologize for the delay in my response. I'm not entirely sure about the exact reason, but in the latest commit, the above test has passed. It's possible that some changes made in the past have had an impact. To resolve this, please install AutoParams 3.1.0, which is the latest version. After installation, you should be able to use it with Java records. Thank you for your understanding.
