### ISSUE TITLE
MockitoCustomizer를 등록하면 OffsetDateTime 타입 데이터를 생성하지 못하는 문제

### ISSUE THREAD

**Issue by 33577** [JavaUnit/AutoParams#281]
안녕하세요 

좋은 라이브러리 만들어주셔서 감사합니다. 
사내에서 잘 쓰고 있습니다 :)

사용하다 다음과 같은 문제를 발견해 제보합니다. 

---

MockitoCustomizer를 등록하면 OffsetDateTime 타입 데이터를 생성하지 못하는 문제입니다. 

## 코드
https://github.com/33577/autoparams-snippet/blob/main/src/test/java/OffsetDateTime_specs.java
``` java
public class OffsetDateTime_specs {
	@AutoSource
	@ParameterizedTest
	void pass(
		OffsetDateTime offsetDateTime
    ) {
		assert true;
	}

	@AutoSource
	@ParameterizedTest
	@Customization(MockitoCustomizer.class)
	void fail(
		OffsetDateTime offsetDateTime
	) {
		assert true;
	}
}
```

### 실행 결과
<img width="1648" alt="스크린샷 2022-03-11 오후 6 45 27" src="https://user-images.githubusercontent.com/34697855/157843345-d4bdeb0f-455f-48e7-9323-18cceebe39ca.png">

## 스택 추적
```
java.lang.NullPointerException
	at java.base/java.time.OffsetDateTime.now(OffsetDateTime.java:247)
	at org.javaunit.autoparams.generator.OffsetDateTimeGenerator.factory(OffsetDateTimeGenerator.java:21)
	at org.javaunit.autoparams.generator.OffsetDateTimeGenerator.generate(OffsetDateTimeGenerator.java:13)
	at org.javaunit.autoparams.generator.CompositeObjectGenerator.lambda$null$0(CompositeObjectGenerator.java:16)
	at org.javaunit.autoparams.generator.ObjectContainer.yieldIfEmpty(ObjectContainer.java:17)
	at org.javaunit.autoparams.generator.CompositeObjectGenerator.lambda$generate$1(CompositeObjectGenerator.java:16)
	at org.javaunit.autoparams.generator.Folder.foldl(Folder.java:13)
	at org.javaunit.autoparams.generator.CompositeObjectGenerator.generate(CompositeObjectGenerator.java:15)
	at org.javaunit.autoparams.generator.CompositeObjectGenerator.lambda$null$0(CompositeObjectGenerator.java:16)
	at org.javaunit.autoparams.generator.ObjectContainer.yieldIfEmpty(ObjectContainer.java:17)
	at org.javaunit.autoparams.generator.CompositeObjectGenerator.lambda$generate$1(CompositeObjectGenerator.java:16)
	at org.javaunit.autoparams.generator.Folder.foldl(Folder.java:13)
	at org.javaunit.autoparams.generator.CompositeObjectGenerator.generate(CompositeObjectGenerator.java:15)
	at org.javaunit.autoparams.generator.CompositeObjectGenerator.lambda$null$0(CompositeObjectGenerator.java:16)
	at org.javaunit.autoparams.generator.ObjectContainer.yieldIfEmpty(ObjectContainer.java:17)
	at org.javaunit.autoparams.generator.CompositeObjectGenerator.lambda$generate$1(CompositeObjectGenerator.java:16)
	at org.javaunit.autoparams.generator.Folder.foldl(Folder.java:13)
	at org.javaunit.autoparams.generator.CompositeObjectGenerator.generate(CompositeObjectGenerator.java:15)
	at org.javaunit.autoparams.mockito.MockitoCustomizer.lambda$null$0(MockitoCustomizer.java:25)
	at org.javaunit.autoparams.generator.ObjectContainer.yieldIfEmpty(ObjectContainer.java:17)
	at org.javaunit.autoparams.mockito.MockitoCustomizer.lambda$customize$1(MockitoCustomizer.java:25)
	at org.javaunit.autoparams.generator.ObjectGenerationContext.generate(ObjectGenerationContext.java:19)
	at org.javaunit.autoparams.ArgumentsGenerator.createThenProcessArgument(ArgumentsGenerator.java:73)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:523)
	at org.javaunit.autoparams.ArgumentsGenerator.createArguments(ArgumentsGenerator.java:68)
	at org.javaunit.autoparams.ArgumentsGenerator.generate(ArgumentsGenerator.java:59)
	at org.javaunit.autoparams.ArgumentsGenerator.generateArguments(ArgumentsGenerator.java:27)
	at org.javaunit.autoparams.AutoArgumentsProvider.provideArguments(AutoArgumentsProvider.java:28)
	at org.junit.jupiter.params.ParameterizedTestExtension.arguments(ParameterizedTestExtension.java:137)
	at org.junit.jupiter.params.ParameterizedTestExtension.lambda$provideTestTemplateInvocationContexts$2(ParameterizedTestExtension.java:88)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:107)
	at org.junit.jupiter.engine.descriptor.TestTemplateTestDescriptor.execute(TestTemplateTestDescriptor.java:42)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
	Suppressed: org.junit.platform.commons.PreconditionViolationException: Configuration error: You must configure at least one set of arguments for this @ParameterizedTest
		at org.junit.platform.commons.util.Preconditions.condition(Preconditions.java:281)
		at org.junit.jupiter.params.ParameterizedTestExtension.lambda$provideTestTemplateInvocationContexts$6(ParameterizedTestExtension.java:94)
		at java.base/java.util.stream.AbstractPipeline.close(AbstractPipeline.java:323)
		at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
		... 51 more

```

## 추정 원인

1. MockitoCustomizer를 등록하지 않은 경우 (PASS)
<img width="1154" alt="image" src="https://user-images.githubusercontent.com/34697855/157843974-11987f82-f822-48e6-b94c-b227618f79a7.png">

2. MockitoCustomizer를 등록한 경우 (FAIL)
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/34697855/157844247-d954f1fb-6a66-4924-b539-31691208e9e1.png">

24번째 줄을 보면, 1.의 경우 `clock`이 `SystemClock`인데, 2.의 경우 `Mock for Clock` 입니다. 
그래서 추후 이 clock의 멤버 값을 이용할 때 NPE가 발생합니다. 
`ClockGenerator`가 존재하지만, `MockitoCustomizer`를 등록하면 `ClockGenerator`를 사용하지 않고 Mock 개체를 생성하는 것이 원인이라 생각합니다. 
(Clock은 추상클래스입니다.)

### 실행 환경
- JDK 11
- autoparams 0.3.1
- autoparams-mockito 0.0.4

**Comment by gyuwon** [comment]
@33577 이 문제를 해결하는 PR을 만들어 주실 수 있을까요?

**Comment by 33577** [comment]
> @33577 이 문제를 해결하는 PR을 만들어 주실 수 있을까요?

오 넵 시도해보겠습니다!
